# -*- coding: utf-8 -*-
"""Example Usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDRtu3d1T07vic9kGyT_P-6k7NnGnyRy
"""

"""
Example Usage: Unified Gas Appliance Generator
==============================================
Demonstrates common use cases for training appliance classification models
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from gas_appliance_generator import HouseholdGasGenerator

def example_1_basic_generation():
    """Example 1: Generate a week of data for a single household"""
    print("=" * 70)
    print("EXAMPLE 1: Basic Week Generation")
    print("=" * 70)

    gen = HouseholdGasGenerator(seed=42)
    week_data = gen.generate_week(people=3)

    print("\nFirst 24 hours:")
    print(week_data.head(24))

    print("\nDaily totals:")
    daily = week_data.groupby('date').agg({
        'stove': 'sum',
        'oven': 'sum',
        'dryer': 'sum',
        'water_heater': 'sum',
        'total': 'sum'
    })
    print(daily)

    return week_data

def example_2_multiple_households():
    """Example 2: Generate data for multiple household configurations"""
    print("\n" + "=" * 70)
    print("EXAMPLE 2: Multiple Household Configurations")
    print("=" * 70)

    # Different household types
    households = [
        {'id': 'H001_single', 'people': 1, 'appliances': ['stove', 'water_heater']},
        {'id': 'H002_couple', 'people': 2, 'appliances': ['stove', 'oven', 'dryer', 'water_heater']},
        {'id': 'H003_family', 'people': 3, 'appliances': ['stove', 'oven', 'dryer', 'water_heater']},
        {'id': 'H004_large', 'people': 5, 'appliances': ['stove', 'oven', 'dryer', 'water_heater']},
    ]

    all_data = []
    for hh in households:
        # Use household ID as seed for reproducibility
        gen = HouseholdGasGenerator(seed=hash(hh['id']) % 10000)
        week = gen.generate_week(
            people=hh['people'],
            appliances=hh.get('appliances'),
            start_date=datetime(2024, 8, 1)
        )
        week['household_id'] = hh['id']
        week['people'] = hh['people']
        all_data.append(week)

    combined = pd.concat(all_data, ignore_index=True)

    print("\nSummary by household:")
    summary = combined.groupby(['household_id', 'people']).agg({
        'total': ['sum', 'mean', 'std']
    })
    print(summary)

    # Save to CSV
    output_file = 'multi_household_week.csv'
    combined.to_csv(output_file, index=False)
    print(f"\n✓ Saved to {output_file}")

    return combined

def example_3_training_dataset():
    """Example 3: Generate large training dataset (30 days, 100 households)"""
    print("\n" + "=" * 70)
    print("EXAMPLE 3: Training Dataset Generation")
    print("=" * 70)

    # Configuration
    n_households = 100
    days_per_household = 30

    print(f"\nGenerating {n_households} households × {days_per_household} days...")

    all_data = []
    for i in range(n_households):
        # Vary household characteristics
        people = np.random.choice([1, 2, 3, 4, 5], p=[0.15, 0.35, 0.25, 0.15, 0.10])

        # Not all households have all appliances
        has_dryer = np.random.random() < 0.75  # 75% have gas dryer
        has_oven = np.random.random() < 0.90   # 90% have gas oven

        appliances = ['stove', 'water_heater']  # Everyone has these
        if has_oven:
            appliances.append('oven')
        if has_dryer:
            appliances.append('dryer')

        # Generate
        gen = HouseholdGasGenerator(seed=i)
        month = gen.generate_month(
            people=people,
            appliances=appliances,
            start_date=datetime(2024, 8, 1),
            days=days_per_household
        )

        month['household_id'] = f'H{i:03d}'
        month['people'] = people
        month['has_dryer'] = has_dryer
        month['has_oven'] = has_oven

        all_data.append(month)

        if (i + 1) % 20 == 0:
            print(f"  Generated {i + 1}/{n_households} households...")

    combined = pd.concat(all_data, ignore_index=True)

    print(f"\n✓ Total rows: {len(combined):,}")
    print(f"✓ Total households: {combined['household_id'].nunique()}")
    print(f"✓ Date range: {combined['date'].min()} to {combined['date'].max()}")

    # Save
    output_file = 'training_dataset_100hh_30d.csv'
    combined.to_csv(output_file, index=False)
    print(f"✓ Saved to {output_file}")

    return combined

def example_4_appliance_patterns():
    """Example 4: Analyze typical appliance usage patterns"""
    print("\n" + "=" * 70)
    print("EXAMPLE 4: Appliance Pattern Analysis")
    print("=" * 70)

    gen = HouseholdGasGenerator(seed=42)
    month = gen.generate_month(people=3, days=30)

    # Hourly patterns by appliance
    print("\nAverage hourly usage by appliance:")
    hourly_avg = month.groupby('hour').agg({
        'stove': 'mean',
        'oven': 'mean',
        'dryer': 'mean',
        'water_heater': 'mean',
        'total': 'mean'
    })
    print(hourly_avg.round(3))

    # Peak hours
    print("\nPeak usage hours:")
    for appliance in ['stove', 'oven', 'dryer', 'water_heater']:
        peak_hour = hourly_avg[appliance].idxmax()
        peak_value = hourly_avg[appliance].max()
        print(f"  {appliance:15s}: Hour {peak_hour:2d} ({peak_value:.3f} therms/hour avg)")

    # Zero-usage analysis
    print("\nZero-usage hours (%):")
    for appliance in ['stove', 'oven', 'dryer', 'water_heater', 'total']:
        zero_pct = (month[appliance] == 0).sum() / len(month) * 100
        print(f"  {appliance:15s}: {zero_pct:.1f}%")

    return month

def example_5_ml_ready_format():
    """Example 5: Format data for ML training"""
    print("\n" + "=" * 70)
    print("EXAMPLE 5: ML-Ready Dataset Format")
    print("=" * 70)

    # Generate data
    gen = HouseholdGasGenerator(seed=42)
    data = gen.generate_month(people=3, days=30)

    # Add features
    data['day_of_week'] = pd.to_datetime(data['date']).dt.dayofweek
    data['is_weekend'] = data['day_of_week'].isin([5, 6]).astype(int)
    data['hour_sin'] = np.sin(2 * np.pi * data['hour'] / 24)
    data['hour_cos'] = np.cos(2 * np.pi * data['hour'] / 24)

    # Create binary labels (appliance active or not)
    for appliance in ['stove', 'oven', 'dryer', 'water_heater']:
        data[f'{appliance}_active'] = (data[appliance] > 0).astype(int)

    print("\nFeature columns:")
    features = ['total', 'hour', 'day_of_week', 'is_weekend', 'hour_sin', 'hour_cos']
    print(f"  {features}")

    print("\nLabel columns (binary):")
    labels = ['stove_active', 'oven_active', 'dryer_active', 'water_heater_active']
    print(f"  {labels}")

    print("\nLabel columns (regression):")
    labels_reg = ['stove', 'oven', 'dryer', 'water_heater']
    print(f"  {labels_reg}")

    print("\nSample data:")
    print(data[features + labels].head(10))

    # Save
    output_file = 'ml_ready_dataset.csv'
    data.to_csv(output_file, index=False)
    print(f"\n✓ Saved to {output_file}")

    return data

def example_6_inject_anomalies():
    """Example 6: Inject anomalies for detection testing"""
    print("\n" + "=" * 70)
    print("EXAMPLE 6: Inject Anomalies for Detection Testing")
    print("=" * 70)

    gen = HouseholdGasGenerator(seed=42)
    data = gen.generate_week(people=3)

    # Normal baseline
    normal_total = data['total'].sum()
    print(f"\nNormal week total: {normal_total:.2f} therms")

    # Anomaly 1: Stove left on (8 hours continuous)
    print("\nInjecting Anomaly 1: Stove left on 18:00-02:00...")
    anomaly_mask = (data['date'] == '2024-08-02') & (data['hour'].between(18, 23))
    data.loc[anomaly_mask, 'stove'] += 0.03  # Add continuous usage
    data.loc[anomaly_mask, 'total'] += 0.03

    anomaly_mask_2 = (data['date'] == '2024-08-03') & (data['hour'].between(0, 1))
    data.loc[anomaly_mask_2, 'stove'] += 0.03
    data.loc[anomaly_mask_2, 'total'] += 0.03

    # Anomaly 2: Burst usage (sudden spike)
    print("Injecting Anomaly 2: Burst at 14:00...")
    burst_mask = (data['date'] == '2024-08-04') & (data['hour'] == 14)
    data.loc[burst_mask, 'stove'] += 0.20  # 10x normal
    data.loc[burst_mask, 'total'] += 0.20

    # Anomaly 3: No-read (missing data)
    print("Injecting Anomaly 3: No-read gap 10:00-12:00...")
    noread_mask = (data['date'] == '2024-08-05') & (data['hour'].between(10, 12))
    data.loc[noread_mask, ['stove', 'oven', 'dryer', 'water_heater', 'total']] = np.nan

    anomalous_total = data['total'].sum()
    print(f"\nAnomalous week total: {anomalous_total:.2f} therms")
    print(f"Increase: {anomalous_total - normal_total:.2f} therms")

    # Label anomalies
    data['is_anomaly'] = 0
    data.loc[anomaly_mask | anomaly_mask_2, 'is_anomaly'] = 1  # Stove left on
    data.loc[burst_mask, 'is_anomaly'] = 2  # Burst
    data.loc[noread_mask, 'is_anomaly'] = 3  # No-read

    # Save
    output_file = 'anomalous_week.csv'
    data.to_csv(output_file, index=False)
    print(f"\n✓ Saved to {output_file}")

    return data

def example_7_compare_occupancy():
    """Example 7: Compare usage across different occupancy levels"""
    print("\n" + "=" * 70)
    print("EXAMPLE 7: Occupancy Comparison")
    print("=" * 70)

    results = []

    for people in range(1, 6):
        gen = HouseholdGasGenerator(seed=42)
        month = gen.generate_month(people=people, days=30)

        summary = {
            'people': people,
            'total_therms': month['total'].sum(),
            'stove_therms': month['stove'].sum(),
            'oven_therms': month['oven'].sum(),
            'dryer_therms': month['dryer'].sum(),
            'water_heater_therms': month['water_heater'].sum(),
            'avg_daily': month.groupby('date')['total'].sum().mean(),
        }
        results.append(summary)

    comparison = pd.DataFrame(results)
    print("\nUsage by occupancy (30-day totals):")
    print(comparison.to_string(index=False))

    # Calculate per-person scaling
    print("\nPer-person daily usage:")
    comparison['per_person_daily'] = comparison['avg_daily'] / comparison['people']
    print(comparison[['people', 'avg_daily', 'per_person_daily']].to_string(index=False))

    return comparison

if __name__ == "__main__":
    print("\n")
    print("*" * 70)
    print("UNIFIED GAS APPLIANCE GENERATOR - USAGE EXAMPLES")
    print("*" * 70)

    # Run all examples
    example_1_basic_generation()
    example_2_multiple_households()
    # example_3_training_dataset()  # Commented out - takes a while
    example_4_appliance_patterns()
    example_5_ml_ready_format()
    example_6_inject_anomalies()
    example_7_compare_occupancy()

    print("\n" + "=" * 70)
    print("ALL EXAMPLES COMPLETE!")
    print("=" * 70)
    print("\nGenerated files:")
    print("  - multi_household_week.csv")
    # print("  - training_dataset_100hh_30d.csv")
    print("  - ml_ready_dataset.csv")
    print("  - anomalous_week.csv")
    print("\n")